### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dohliam** [kovacsv/JS1K#1]
Hi kovacsv, thanks for sharing your js1k entries, they're pretty cool! :+1: I notice you haven't included a license. Would it be possible to release them under a free license so that they can be included in the [openjs1k](https://github.com/dohliam/openjs1k) project? Even if you don't plan on using a free license, having a license of some kind would help people know whether or not they can reuse your work. :smile:

**Comment by kovacsv** [comment]
Hi dohliam,

I have added MIT license, so feel free to include my work in your project.

Thanks,
Viktor
